channels:
- conda-forge
dependencies:
- glmnet==2.2.1
- pip:
  - numpy==1.22.1
  - bambi==0.9.3
  - formulae==0.3.4
  - tabulate==0.9.0
  - nlopt==2.7.1
  - numpyro==0.12.1
  - tensorflow==2.11.0 
  - tensorflow-probability==0.19.0
  - jax==0.4.23
  - jaxlib==0.4.23